SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
FPS = 60

TITLE = "Moonbound Prototype"

CAMERA_SMOOTHING = 0.12

MAP_0_WIDTH = 11500
MAP_0_HEIGHT = 720

MAP_1_WIDTH = 1500
MAP_1_HEIGHT = 720

MAP_2_WIDTH = 11500
MAP_2_HEIGHT = 1400

MAP_4_WIDTH = 14500
MAP_4_HEIGHT = 1100

MAP_5_WIDTH = 1500
MAP_5_HEIGHT = 720

MAP_6_WIDTH = 12000
MAP_6_HEIGHT = 720

MAP_7_WIDTH = 1800
MAP_7_HEIGHT = 720

MAP_8_WIDTH = 11000
MAP_8_HEIGHT = 900

BOSS_ROOM_MIN_X = 8699
BOSS_ROOM_MAX_X = 11000
BOSS_ROOM_MIN_Y = 0
BOSS_ROOM_MAX_Y = 900
BOSS_ROOM_WIDTH = BOSS_ROOM_MAX_X - BOSS_ROOM_MIN_X
BOSS_ROOM_HEIGHT = BOSS_ROOM_MAX_Y - BOSS_ROOM_MIN_Y
BOSS_PLAYER_SPAWN_X = 8900
BOSS_PLAYER_SPAWN_Y = 720
BOSS_CORE_SCALE = 0.45
BOSS_HEAD_SCALE = 0.38
BOSS_WEAK_POINT_FRAME_COUNT = 6

DOOR_WIDTH = 60
DOOR_HEIGHT = 100

SHOP_PRODUCT_SLOT_COUNT = 5
SHOP_RANDOM_SEED_ENABLED = False

GAME_OVER_POPUP_WIDTH = 520
GAME_OVER_POPUP_HEIGHT = 260

DEBUG_MODE = False
DEBUG_DRAW_HITBOXES = False
DEBUG_ENEMY_HITBOX = False
DEBUG_UNLIMITED_HP = False
DEBUG_UNLIMITED_MANA = False

GRAVITY = 0.8

PLAYER_SPEED = 5
PLAYER_JUMP_SPEED = -16

PLAYER_DASH_SPEED = 14
PLAYER_DASH_TIME = 0.15
PLAYER_DASH_COOLDOWN = 0.6

PLAYER_MAX_HP = 100
PLAYER_MAX_MANA = 100
PLAYER_INVINCIBLE_TIME = 0.8

PLAYER_CRIT_CHANCE = 0.15
PLAYER_CRIT_DAMAGE = 1.5
PLAYER_BONUS_ATTACK_PERCENT = 0.0

PLAYER_ATTACK_COOLDOWN = 0.35
PLAYER_ATTACK_TIME = 0.12
PLAYER_ATTACK_RANGE = 55
PLAYER_ATTACK_WIDTH = 55
PLAYER_ATTACK_HEIGHT = 40

LIGHT_IDLE_FRAME_COUNT = 6
LIGHT_WALK_FRAME_COUNT = 6
LIGHT_JUMP_FRAME_COUNT = 6
LIGHT_DASH_FRAME_COUNT = 4
LIGHT_ATTACK_FRAME_COUNT = 6
LIGHT_IDLE_ANIMATION_SPEED = 0.12
LIGHT_WALK_ANIMATION_SPEED = 0.10
LIGHT_JUMP_ANIMATION_SPEED = 0.12
LIGHT_DASH_ANIMATION_SPEED = 0.06
LIGHT_ATTACK_ANIMATION_SPEED = 0.05
LIGHT_PLAYER_TARGET_WIDTH = 96
LIGHT_PLAYER_TARGET_HEIGHT = 96
LIGHT_ATTACK_TARGET_WIDTH = 320
LIGHT_ATTACK_TARGET_HEIGHT = 220
LIGHT_ATTACK_CHARACTER_HEIGHT = 125
LIGHT_ANIM_OFFSET_X = 15
LIGHT_ANIM_OFFSET_Y = 0
LIGHT_ATTACK_OFFSET_X = 0
LIGHT_ATTACK_OFFSET_Y = 0

HEAVY_IDLE_FRAME_COUNT = 6
HEAVY_WALK_FRAME_COUNT = 6
HEAVY_JUMP_FRAME_COUNT = 6
HEAVY_DASH_FRAME_COUNT = 4
HEAVY_ATTACK_FRAME_COUNT = 6
HEAVY_IDLE_ANIMATION_SPEED = 0.13
HEAVY_WALK_ANIMATION_SPEED = 0.12
HEAVY_JUMP_ANIMATION_SPEED = 0.12
HEAVY_DASH_ANIMATION_SPEED = 0.07
HEAVY_ATTACK_ANIMATION_SPEED = 0.09
HEAVY_PLAYER_TARGET_WIDTH = 104
HEAVY_PLAYER_TARGET_HEIGHT = 104
HEAVY_ATTACK_TARGET_WIDTH = 480
HEAVY_ATTACK_TARGET_HEIGHT = 280
HEAVY_ATTACK_CHARACTER_HEIGHT = 140
HEAVY_ANIM_OFFSET_X = 0
HEAVY_ANIM_OFFSET_Y = 0
HEAVY_ATTACK_OFFSET_X = 0
HEAVY_ATTACK_OFFSET_Y = 0

SHOOTER_IDLE_FRAME_COUNT = 6
SHOOTER_WALK_FRAME_COUNT = 6
SHOOTER_JUMP_FRAME_COUNT = 6
SHOOTER_DASH_FRAME_COUNT = 6
SHOOTER_ATTACK_FRAME_COUNT = 6
SHOOTER_IDLE_ANIMATION_SPEED = 0.12
SHOOTER_WALK_ANIMATION_SPEED = 0.10
SHOOTER_JUMP_ANIMATION_SPEED = 0.12
SHOOTER_DASH_ANIMATION_SPEED = 0.07
SHOOTER_ATTACK_ANIMATION_SPEED = 0.1
SHOOTER_PLAYER_TARGET_WIDTH = 96
SHOOTER_PLAYER_TARGET_HEIGHT = 96
SHOOTER_ATTACK_TARGET_WIDTH = 420
SHOOTER_ATTACK_TARGET_HEIGHT = 260
SHOOTER_ATTACK_CHARACTER_HEIGHT = 125
SHOOTER_ANIM_OFFSET_X = 0
SHOOTER_ANIM_OFFSET_Y = 0
SHOOTER_ATTACK_OFFSET_X = 0
SHOOTER_ATTACK_OFFSET_Y = 0

SHIELD_IDLE_FRAME_COUNT = 6
SHIELD_WALK_FRAME_COUNT = 6
SHIELD_JUMP_FRAME_COUNT = 6
SHIELD_DASH_FRAME_COUNT = 6
SHIELD_ATTACK_FRAME_COUNT = 6
SHIELD_IDLE_ANIMATION_SPEED = 0.13
SHIELD_WALK_ANIMATION_SPEED = 0.12
SHIELD_JUMP_ANIMATION_SPEED = 0.12
SHIELD_DASH_ANIMATION_SPEED = 0.08
SHIELD_ATTACK_ANIMATION_SPEED = 0.10
SHIELD_PLAYER_TARGET_WIDTH = 104
SHIELD_PLAYER_TARGET_HEIGHT = 104
SHIELD_ATTACK_TARGET_WIDTH = 420
SHIELD_ATTACK_TARGET_HEIGHT = 260
SHIELD_ATTACK_CHARACTER_HEIGHT = 130
SHIELD_ANIM_OFFSET_X = 0
SHIELD_ANIM_OFFSET_Y = 0
SHIELD_ATTACK_OFFSET_X = 0
SHIELD_ATTACK_OFFSET_Y = 0

GRAPPLE_IDLE_FRAME_COUNT = 6
GRAPPLE_WALK_FRAME_COUNT = 6
GRAPPLE_JUMP_FRAME_COUNT = 6
GRAPPLE_DASH_FRAME_COUNT = 6
GRAPPLE_ATTACK_FRAME_COUNT = 6
GRAPPLE_IDLE_ANIMATION_SPEED = 0.12
GRAPPLE_WALK_ANIMATION_SPEED = 0.10
GRAPPLE_JUMP_ANIMATION_SPEED = 0.12
GRAPPLE_DASH_ANIMATION_SPEED = 0.07
GRAPPLE_ATTACK_ANIMATION_SPEED = 0.15
GRAPPLE_PLAYER_TARGET_WIDTH = 104
GRAPPLE_PLAYER_TARGET_HEIGHT = 104
GRAPPLE_ATTACK_TARGET_WIDTH = 600
GRAPPLE_ATTACK_TARGET_HEIGHT = 280
GRAPPLE_ATTACK_CHARACTER_HEIGHT = 130
GRAPPLE_ANIM_OFFSET_X = 0
GRAPPLE_ANIM_OFFSET_Y = 0
GRAPPLE_ATTACK_OFFSET_X = 0
GRAPPLE_ATTACK_OFFSET_Y = 0

TEST_WEAPON_DAMAGE = 20

ENEMY_MAX_HP = 60
ENEMY_ATTACK_COOLDOWN = 1.0
ENEMY_ATTACK_RANGE = 45
ENEMY_ATTACK_TIME = 0.2
ENEMY_DAMAGE = 10
ENEMY_RESPAWN_TIME = 2.0
ARCHER_VISUAL_SCALE = 1.35
MELEE_VISUAL_SCALE = 1.45
MELEE_DRAW_OFFSET_Y = 35
ARCHER_DRAW_OFFSET_Y = 8
MELEE_SPAWN_OFFSET_Y = 0
ARCHER_SPAWN_OFFSET_Y = 8
ARCHER_HP_BAR_OFFSET_Y = -12
MELEE_HP_BAR_OFFSET_Y = -12

HP_BAR_WIDTH = 220
HP_BAR_HEIGHT = 22
MANA_BAR_WIDTH = 220
MANA_BAR_HEIGHT = 16

COIN_VALUE = 1
COIN_RADIUS = 8
COIN_PICKUP_RANGE = 10
COIN_GRAVITY = 0.4
COIN_BOUNCE_SPEED = -5

NORMAL_PARRY_ACTIVE_TIME = 0.5
NORMAL_PARRY_COOLDOWN = 1.2
NORMAL_PARRY_STUN_TIME = 0.8

WEAPON_SPECIAL_COOLDOWN = 1.0

PROJECTILE_LIFETIME = 2.0

GRAPPLE_PULL_SPEED = 12
GRAPPLE_ENEMY_FINAL_STUN_TIME = 1.0
GRAPPLE_PLAYER_PULL_SPEED = 14
FULCRUM_RADIUS = 14

WEAPON_BOX_WIDTH = 130
WEAPON_BOX_HEIGHT = 38
WEAPON_BOX_GAP = 10

SHIELD_THROW_SPEED = 8
SHIELD_RETURN_SPEED = 10
SHIELD_THROW_MAX_DISTANCE = 260
SHIELD_THROW_SIZE = 28
SHIELD_THROW_LIFETIME = 3.0

SHIELD_THROW_CAN_HIT_ON_RETURN = True
SHIELD_THROW_HIT_COOLDOWN = 0.15

DEBUG_PROJECTILES = False
SHOOTER_BULLET_PATH = "assets/projectiles/shooter_bullet.png"
SHOOTER_BULLET_HIT_PATH = "assets/projectiles/shooter_bullet_hit.png"
SHOOTER_BULLET_FRAME_COUNT = 6
SHOOTER_BULLET_FRAME_WIDTH = 96
SHOOTER_BULLET_FRAME_HEIGHT = 48
SHOOTER_BULLET_HIT_FRAME_WIDTH = 96
SHOOTER_BULLET_HIT_FRAME_HEIGHT = 96
SHOOTER_BULLET_MUZZLE_OFFSET_X = 55
SHOOTER_BULLET_MUZZLE_OFFSET_Y = -10
SHOOTER_BULLET_SPEED = 12
SHOOTER_BULLET_MAX_DISTANCE = 500

AUTO_GRAPPLE_DURATION = 0.9
AUTO_GRAPPLE_ARC_HEIGHT = 180
FULCRUM_INTERACT_DISTANCE = 120

SHOP_INTERACT_DISTANCE = 100

SHOP_HEAL_COST = 10
SHOP_MANA_COST = 10

SHOP_MAX_HP_COST = 30
SHOP_MAX_HP_INCREASE = 20

SHOP_MAX_MANA_COST = 25
SHOP_MAX_MANA_INCREASE = 20

SHOP_CRIT_CHANCE_COST = 40
SHOP_CRIT_CHANCE_INCREASE = 0.05
SHOP_CRIT_CHANCE_MAX = 0.75

SHOP_CRIT_DAMAGE_COST = 45
SHOP_CRIT_DAMAGE_INCREASE = 0.25
SHOP_CRIT_DAMAGE_MAX = 3.0

SHOP_ATTACK_POTION_COST = 50
SHOP_ATTACK_POTION_INCREASE = 0.10
SHOP_ATTACK_POTION_MAX = 1.0

SHOP_WEAPON_COST = 50
SHOP_SKILL_COST = 50

# General skill settings
SKILL_EFFECT_LIFETIME = 0.25
SKILL_EFFECT_FRAME_COUNT = 6
SKILL_EFFECT_FRAME_WIDTH = 500
SKILL_EFFECT_FRAME_HEIGHT = 225

# Time Freeze
TIME_FREEZE_RADIUS = 220
TIME_FREEZE_DURATION = 3.0
TIME_FREEZE_VISUAL_DURATION = 1.0
TIME_FREEZE_STUN_DURATION = 3.0

# Orbit Blades Auto-Aim Launcher
ORBIT_BLADE_COUNT = 3
ORBIT_BLADE_DAMAGE = 15
ORBIT_BLADE_RADIUS = 55
ORBIT_BLADE_SIZE = 14
ORBIT_BLADE_ORBIT_SPEED = 5.0
ORBIT_BLADE_READY_TIME = 0.5
ORBIT_BLADE_FIRE_DELAY = 0.15
ORBIT_BLADE_PROJECTILE_SPEED = 10
ORBIT_BLADE_TARGET_RANGE = 450
ORBIT_BLADE_LIFETIME = 2.0

# Energy Beam
ENERGY_BEAM_DAMAGE = 45
ENERGY_BEAM_RANGE = 320
ENERGY_BEAM_HEIGHT = 36

EXECUTE_PARRY_WINDOW = 2.0

# Soul Anchor
SOUL_ANCHOR_DURATION = 6.0
SOUL_ANCHOR_RETURN_COST = 20

TIME_FREEZE_READY_PATH = "assets/skills/time_freeze/time_freeze_ready.png"
TIME_FREEZE_ACTION_PATH = "assets/skills/time_freeze/time_freeze_action.png"
TIME_FREEZE_LOOP_PATH = "assets/skills/time_freeze/time_freeze_loop.png"

ORBIT_BLADES_READY_PATH = "assets/skills/orbit_blades/orbit_blades_ready.png"
ORBIT_BLADE_PROJECTILE_PATH = "assets/skills/orbit_blades/orbit_blade_projectile.png"
ORBIT_BLADE_HIT_PATH = "assets/skills/orbit_blades/orbit_blade_hit.png"

ENERGY_BEAM_READY_PATH = "assets/skills/beam_attack/energy_beam_ready.png"
ENERGY_BEAM_ATTACK_PATH = "assets/skills/beam_attack/energy_beam_attack_clean.png"
ENERGY_BEAM_HIT_PATH = "assets/skills/beam_attack/energy_beam_hit.png"
ENERGY_BEAM_ATTACK_SCALE = 0.45
ENERGY_BEAM_ATTACK_OFFSET_X = 0
ENERGY_BEAM_ATTACK_OFFSET_Y = 0
BOSS_HIT_EFFECT_SCALE = 0.35
# Edit HAND_SLAM_WARNING_SCALE to resize.
HAND_SLAM_WARNING_SCALE = 0.35
# Edit OFFSET_X / OFFSET_Y to move the warning position.
HAND_SLAM_WARNING_OFFSET_X = 0
HAND_SLAM_WARNING_OFFSET_Y = 0
HAND_SLAM_WARNING_FRAME_TIME = 0.08
HAND_SLAM_WARNING_ANIM_SPEED = HAND_SLAM_WARNING_FRAME_TIME
BOSS_BEAM_ATTACK_SCALE = 0.45
BOSS_BEAM_READY_SCALE = 0.45
BOSS_BEAM_SOURCE_ANCHOR = "center"

SOUL_ANCHOR_READY_PATH = "assets/skills/soul_anchor/soul_anchor_ready.png"
SOUL_ANCHOR_PLACE_PATH = "assets/skills/soul_anchor/soul_anchor_place.png"
SOUL_ANCHOR_LOOP_PATH = "assets/skills/soul_anchor/soul_anchor_loop.png"
SOUL_ANCHOR_RETURN_PATH = "assets/skills/soul_anchor/soul_anchor_return.png"

PIXELATE_GAME = False
PIXEL_WIDTH = 500
PIXEL_HEIGHT = 225
