SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
FPS = 60

TITLE = "Moonbound Prototype"

GRAVITY = 0.8

PLAYER_SPEED = 5
PLAYER_JUMP_SPEED = -16

PLAYER_DASH_SPEED = 14
PLAYER_DASH_TIME = 0.15
PLAYER_DASH_COOLDOWN = 0.6

PLAYER_MAX_HP = 100
PLAYER_MAX_MANA = 100

PLAYER_CRIT_CHANCE = 0.15
PLAYER_CRIT_DAMAGE = 1.5
PLAYER_BONUS_ATTACK_PERCENT = 0.0
