SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
FPS = 60

TITLE = "Moonbound Prototype"

GRAVITY = 0.8

PLAYER_SPEED = 5
PLAYER_JUMP_SPEED = -16

PLAYER_DASH_SPEED = 14
PLAYER_DASH_TIME = 0.15
PLAYER_DASH_COOLDOWN = 0.6

PLAYER_MAX_HP = 100
PLAYER_MAX_MANA = 100
PLAYER_INVINCIBLE_TIME = 0.8

PLAYER_CRIT_CHANCE = 0.15
PLAYER_CRIT_DAMAGE = 1.5
PLAYER_BONUS_ATTACK_PERCENT = 0.0

PLAYER_ATTACK_COOLDOWN = 0.35
PLAYER_ATTACK_TIME = 0.12
PLAYER_ATTACK_RANGE = 55
PLAYER_ATTACK_WIDTH = 55
PLAYER_ATTACK_HEIGHT = 40

TEST_WEAPON_DAMAGE = 20

ENEMY_MAX_HP = 60
ENEMY_ATTACK_COOLDOWN = 1.0
ENEMY_ATTACK_RANGE = 45
ENEMY_ATTACK_TIME = 0.2
ENEMY_DAMAGE = 10
ENEMY_RESPAWN_TIME = 2.0

HP_BAR_WIDTH = 220
HP_BAR_HEIGHT = 22
MANA_BAR_WIDTH = 220
MANA_BAR_HEIGHT = 16

COIN_VALUE = 5
COIN_RADIUS = 8
COIN_PICKUP_RANGE = 10
COIN_GRAVITY = 0.4
COIN_BOUNCE_SPEED = -5

STAMINA_MAX = 100
STAMINA_BLOCK_DRAIN_PER_SECOND = 20
STAMINA_BLOCK_HIT_COST = 25
STAMINA_RECOVER_PER_SECOND = 30
STAMINA_RECOVER_DELAY = 0.8
STAMINA_RECOVER_DELAY_AFTER_HIT = 1.2
GUARD_BREAK_TIME = 1.0

NORMAL_PARRY_ACTIVE_TIME = 0.25
NORMAL_PARRY_COOLDOWN = 1.2
NORMAL_PARRY_STUN_TIME = 0.8

WEAPON_SPECIAL_COOLDOWN = 1.0

PROJECTILE_LIFETIME = 2.0

GRAPPLE_PULL_SPEED = 12
GRAPPLE_ENEMY_FINAL_STUN_TIME = 1.0
GRAPPLE_PLAYER_PULL_SPEED = 14
FULCRUM_RADIUS = 14

WEAPON_BOX_WIDTH = 130
WEAPON_BOX_HEIGHT = 38
WEAPON_BOX_GAP = 10

SHIELD_THROW_SPEED = 8
SHIELD_RETURN_SPEED = 10
SHIELD_THROW_MAX_DISTANCE = 260
SHIELD_THROW_SIZE = 28
SHIELD_THROW_LIFETIME = 3.0

SHIELD_THROW_CAN_HIT_ON_RETURN = True
SHIELD_THROW_HIT_COOLDOWN = 0.15

AUTO_GRAPPLE_DURATION = 0.9
AUTO_GRAPPLE_ARC_HEIGHT = 180
FULCRUM_INTERACT_DISTANCE = 120
